final products = [
  {
    'id': 1,
    'namaProduk': 'Kopi',
    'hargaProduk': 40000,
    'jumlahProduk': 5,
    'stok': 10,
    'gambarProduk': 'assets/chicken.jpg',
  },
  {
    'id': 2,
    'namaProduk': 'Kopi',
    'hargaProduk': 20000,
    'jumlahProduk': 5,
    'stok': 10,
    'gambarProduk': 'assets/chicken.jpg',
  },
  {
    'id': 3,
    'namaProduk': 'Kopi',
    'hargaProduk': 20000,
    'jumlahProduk': 5,
    'stok': 10,
    'gambarProduk': 'assets/chicken.jpg',
  },
  {
    'id': 4,
    'namaProduk': 'Kopi',
    'hargaProduk': 20000,
    'jumlahProduk': 5,
    'stok': 10,
    'gambarProduk': 'assets/chicken.jpg',
  },
  {
    'id': 5,
    'namaProduk': 'Kopi',
    'hargaProduk': 20000,
    'jumlahProduk': 5,
    'stok': 10,
    'gambarProduk': 'assets/chicken.jpg',
  },
  {
    'id': 6,
    'namaProduk': 'Kopi',
    'hargaProduk': 20000,
    'jumlahProduk': 5,
    'stok': 10,
    'gambarProduk': 'assets/chicken.jpg',
  },
];
